repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
        exclude: ^.*\.(lock)$||^docs\/
      - id: mixed-line-ending
        exclude: ^.*\.(lock)$||^docs\/
      - id: detect-private-key


  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        files: ^src/.*\.(ts|tsx|js|css|html|json)$
        args: [ '--config=.prettierrc.js', '--ignore-path=.prettierignore' ]


  - repo: local
    hooks:
      - id: eslint
        name: ESlint
        entry: sh -c "yarn install && npm run lint:fix"
        language: system
        pass_filenames: false