version: "3.4"

services:
  dmss:
    image: datamodelingtool.azurecr.io/dmss:${DMSS_TAG:-v1.26.0}
    restart: unless-stopped
    environment:
      AUTH_ENABLED: 0
      ENVIRONMENT: local
      REDIS_PASSWORD: maf
      LOGGING_LEVEL: INFO
      MONGO_USERNAME: maf
      MONGO_PASSWORD: maf
      SECRET_KEY: sg9aeUM5i1JO4gNN8fQadokJa3_gXQMLBjSGGYcfscs= # Don't reuse this in production...
      RESET_DATA_SOURCE: "false"
    ports:
      - "5002:5000"
    depends_on:
      - db
      - redis
  redis:
    image: bitnami/redis:latest
    environment:
        REDIS_PASSWORD: maf


  db:
    image: mongo:3.6
    command: mongod --quiet
    volumes:
      - ./dmss-data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf

  job-api:
    image: datamodelingtool.azurecr.io/dm-job:${JOB_API_TAG:-v1.6.4}
    restart: unless-stopped
    environment:
      SCHEDULER_REDIS_HOST: redis
      SCHEDULER_REDIS_PASSWORD: maf
      DMSS_API: http://dmss:5000
      ENVIRONMENT: local
      AUTH_ENABLED: 0
    depends_on:
      - redis
    volumes:
      - ./job_handlers:/code/src/job_handler_plugins
    ports:
      - "5001:5000"
