version: "3.4"

services:
  dmss:
    image: datamodelingtool.azurecr.io/dmss:v1.0.0
    restart: unless-stopped
    environment:
      AUTH_ENABLED: 0
      ENVIRONMENT: local
      LOGGING_LEVEL: DEBUG
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf
      SECRET_KEY: sg9aeUM5i1JO4gNN8fQadokJa3_gXQMLBjSGGYcfscs= # Don't reuse this in production...
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mongo:3.4
    command: mongod --quiet
    volumes:
      - ./dmss-data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf

  job-api:
    image: datamodelingtool.azurecr.io/dm-job:v1.0.4
    restart: unless-stopped
    environment:
      DMSS_API: http://dmss:5000
      API_DEBUG: 1
      ENVIRONMENT: local
      #SIMA_LICENSE: |
    depends_on:
      - job-store
    volumes:
      - ./job_handlers:/code/src/job_handler_plugins
    ports:
      - "5001:5000"

#  db-ui:
#    image: mongo-express:1.0.0-alpha
#    restart: unless-stopped
#    ports:
#      - "8082:8081"
#    environment:
#      ME_CONFIG_MONGODB_SERVER: db
#      ME_CONFIG_MONGODB_ADMINUSERNAME: maf
#      ME_CONFIG_MONGODB_ADMINPASSWORD: maf
#      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

  job-store:
    image: redis:6.2.5-alpine
    command: "redis-server --save 30 1 --loglevel notice"
    #    volumes:
    #     - ./redis_data:/data
