on:
  workflow_call:
    inputs:
      asLatest:
        description: 'Run with latest images and packages'
        required: true
        type: boolean
      useLocal:
        description: 'If true, checkout main from repo. If false, get from npm'
        required: true
        type: boolean

env:
  APP_NAME: 'my-app'
  DC_ENV: "${{ inputs.asLatest && 'DMSS_TAG=latest JOB_API_TAG=latest' || '' }}"

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install dm-cli'
        run: pip install dm-cli

      - name: 'Install pm2'
        run: npm add -g pm2

      - name: 'Install serve'
        run: npm add -g serve

      - name: 'Create a new application from main'
        if: inputs.useLocal
        uses: actions/checkout@v4
        with:
          path: ${{ env.APP_NAME }}

      - name: 'Create a new application from npmjs'
        if: ${{ !inputs.useLocal }}
        run: npx @development-framework/create-dm-app $APP_NAME

      - name: 'Install dependencies'
        working-directory: ${{ env.APP_NAME }}
        run: npm install

      - name: 'Start DMSS'
        working-directory: ${{ env.APP_NAME }}
        run: |
          eval "$DC_ENV docker-compose pull"
          eval "$DC_ENV docker-compose up --build --detach"
          eval "$DC_ENV docker-compose logs"

      - name: 'Run reset app'
        working-directory: ${{ env.APP_NAME }}
        run: ./reset-app.sh

      - name: 'Install latest plugins'
        if: inputs.asLatest
        working-directory: ${{ env.APP_NAME }}
        run: |
          npm add @development-framework/dm-core
          npm add @development-framework/dm-core-plugins

      - name: 'Start the web application'
        working-directory: ${{ env.APP_NAME }}
        run: |
          npm run build
          pm2 start npm -- run serve

      - name: 'Curl frontend and backend'
        id: curl
        run: |
          sleep 5
          echo "frontend-status-code=$(curl -s -o /dev/null -w "%{http_code}" localhost:3000)" >> $GITHUB_OUTPUT
          echo "backend-status-code=$(curl -s -o /dev/null -w "%{http_code}" localhost:5002/api/healthcheck)" >> $GITHUB_OUTPUT

      - name: 'Stop DMSS'
        working-directory: ${{ env.APP_NAME }}
        run: docker-compose stop

      - name: 'Stop the web application'
        run: pm2 stop 0

      - name: 'Set workflow status'
        if: ${{ steps.curl.outputs.frontend-status-code != 200 || steps.curl.outputs.backend-status-code != 200 }}
        uses: actions/github-script@v6
        with:
          script: core.setFailed('Backend returned status code ${{ steps.curl.outputs.backend-status-code }}. Frontend returned status code ${{ steps.curl.outputs.frontend-status-code }}')
