name: 'On push to main'

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: on-push-main

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  release-please:
    needs: tests
    uses: ./.github/workflows/create-release-pr.yaml

  release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ./.github/workflows/publish-to-registry.yaml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
