on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
  # Workflow call is used for called from another workflow
  workflow_call:



jobs:
  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: "Install web packages"
        run: |
          yarn install

      - name: "Test for typescript errors"
        run: yarn tsc
